steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-coe-msp-sandbox/gcpdiag:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-coe-msp-sandbox/gcpdiag:$COMMIT_SHA']