steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-coe-msp-sandbox/gcpdiag:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-coe-msp-sandbox/gcpdiag:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'gcpdiag-test-3', '--image=gcr.io/gcp-coe-msp-sandbox/gcpdiag:$COMMIT_SHA', '--update-secrets=/app/gcpdiag/cloud-run-test-key/cloud-run-test-key=cloud-run-test-key:latest,jira_token=jira-token-cloud-run-test:latest', '--region=europe-central2', '--port=8000']
